stages:
  - deploy

deploy:
  stage: deploy
  image: amazon/aws-cli:2.4.0 # 使用AWS CLI镜像
  script:
    # 配置AWS CLI
    - aws configure set aws_access_key_id $COS_SECRET_ID
    - aws configure set aws_secret_access_key $COS_SECRET_KEY
    - aws configure set default.region $COS_REGION
    # 上传文件
    - aws s3 sync ./ s3://$COS_BUCKET
  only:
    - branch_t
