stages:
  - deploy

deploy:
  stage: deploy
  image: curlimages/curl:7.77.0 # 使用Curl镜像
  script:
    # 安装coscmd
    - curl https://cdn.jsdelivr.net/gh/tencentyun/coscmd/release/coscmd_linux64 -o /usr/local/bin/coscmd
    - chmod +x /usr/local/bin/coscmd
    # 配置coscmd
    - coscmd config -a $COS_SECRET_ID -s $COS_SECRET_KEY -r $COS_REGION -b $COS_BUCKET
    # 上传文件
    - coscmd upload ./ / --recursive
  only:
    - branch_t
