export default function Head() {
  return (
    <>
      <title>home</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo.svg" />
    </>
  );
}

// export async function generateStaticParams() {
//   const posts = await getPosts();

//   return posts.map((post) => ({
//     slug: post.slug,
//   }));
// }
